# 异常处理

<!-- MarkdownTOC -->
<!-- TOC -->
- [异常处理](#异常处理)   
 - [1. 异常处理的体系](#1-异常处理的体系)    
 	 - [1.1 Error与Exception的区别：](#11-error与exception的区别)      
  	 - [1.2 Exception的子类](#12-exception的子类)        
   	 - [1.3 常见的RuntimeException](#13-常见的runtimeexception)       
   	 - [1.4 常见的非RuntimeException](#14-常见的非runtimeexception)       
     - [1.5 常见的Error](#15-常见的error)      
     -  [【补充】 内充泄漏与内存溢出](#补充-内充泄漏与内存溢出)  
    - [2. 异常处理机制](#2-异常处理机制)      
		 - [2.1 处理机制流程](#21-处理机制流程)            
   		 - [2.2 流程演示](#22-流程演示)       
    	- [2.3 一道例题](#23-一道例题)      
    	- [2.4 throws、throw、try、catch、finally分别代表什么意义？](#24-throwsthrowtrycatchfinally分别代表什么意义)      
   		 - [2.5 finally代码是在return之后还是之前执行？](#25-finally代码是在return之后还是之前执行)      
    	- [2.6 Java中final,finalize,finally关键字的区别？](#26-java中finalfinalizefinally关键字的区别)   
  - [3.  异常处理的原则](#3--异常处理的原则)<!-- /TOC -->

<!-- /MarkdownTOC -->



## 1. 异常处理的体系
![](https://s2.ax1x.com/2019/06/04/Vt3KAO.jpg)


> 
> Throwable是所有异常的父类，异常分为Error与Exception


### 1.1 Error与Exception的区别：
> 
> Error是程序无法处理的系统错误，编译器不做检查，一般需要程序终止 【StackOverflowError, OutOfMemoryError】
> 
> Exception是程序可以处理的错误，可以被捕获，恢复 。他们的本质区别就是可不可以被程序处理恢复


<br>


### 1.2 Exception的子类

<br>

> 
> RuntimeException: 不可预知的，程序应当避免，如空指针异常，调用时候先判断是否是空指针就避免了出现异常
> 
> 非runtimeException： 可预知的，编译器检验的异常，如果不处理，编译器无法通过  
> 
> 从责任角度判断：error需要JVM承担责任，RuntimeException是程序应该承担的责任，非runtimeException属于编译器应该承担的责任   



<br>


### 1.3 常见的RuntimeException

<br>

>  RuntimeException:  
> 
>  1.NullPointException   :空指针异常
>  
>  2.ClassCastException   ：类型转换异常
>  
>  3.IllegalArgumentException: 传递非法参数异常 [一般是版本不兼容]
>  
>  4.IndexOutOfBoundsException:下标越界异常 
> 
> 5.NumberFormatException:数字格式异常 

>6. ArithmeticException 算数异常

<br>

    public class RuntimeExceptions {
    	public static void main(String[] args) {
      		 //java.lang.NullPointerException
      		 	String str =null;
       		 	str.getBytes();
        	//java.lang.ArrayIndexOutOfBoundsException:
        		int [] arr =new int [10];
        		arr[10]=0;
        	//java.lang.NumberFormatException
        		String str1="ssss";
        		Integer.valueOf(str1);
        	//java.lang.ClassCastException:
         		 Object integer =new Integer(10);
       			 System.out.println((String)integer);
    	}
	}






<br>


### 1.4 常见的非RuntimeException

<br>


> 非RuntimeException
> 
> 1.ClassNotFoundException :找不到指定的类异常
> 
> 2.IOExcepton  ：IO操作异常 


<br>


      // java.lang.ClassNotFoundException: com.sql
       		 try {
          	  Class.forName("com.sql");
        	} catch (ClassNotFoundException e) {
        	    e.printStackTrace();
        	}

        //java.io.FileNotFoundException: a\s (系统找不到指定的路径。)
             File file =new File("a/s");
             try {
                 InputStream  is  =new FileInputStream(file);
             } catch (FileNotFoundException e) {
                 e.printStackTrace();
             }

<br>


### 1.5 常见的Error

<br>

> 
> 1.NoClassDefFoundError：【框架中依赖的class没有引入】
> 
> 2.StackOverflowError: 【深度递归导致栈深太深，可能是没有设置结束条件，如果代码没问题，将递归改为for循环】
> 
> 3.OutOfMemory:【创建的线程太多了，导致内存溢出】

### 【补充】 内充泄漏与内存溢出  

<br>

> 内存溢出：表示所需要的内存超过了可以使用的内存大小
> 
> 内存泄漏：某资源用来，他占用的内存无法释放

<br>

## 2. 异常处理机制 

<br>

### 2.1 处理机制流程 
 
> 
>  一般分为两个流程，抛出异常与捕获异常 
> 
> 运行时出现错误，然后创建一个异常对象，抛出异常交给运行时系统
> 
> 系统寻找合适的异常处理器处理，如果没有的话终止运行，有的话由异常处理器处理

<br>

### 2.2 流程演示 
<br>

    public class TryCatchFinallyDemo {
   		 public static void main(String[] args) {
       		 System.out.println(getNum());
   		 }
    	public static  int getNum(){
        	try{
            	int i= 10/0;
            	return 1;
        	}catch (ArithmeticException e){
           		 System.out.println("ArithmeticException错误");
            	return 2;
        	}catch (Exception e ){
            	System.out.println("Exception错误");
           		 return 3;
       		 }finally{
           		 return 4;
        		}
    	}
	}	


> 输出结果：ArithmeticException错误     4 
> 
> 出现错误则创建错误类型对象包含错误信息以及程序运行状态抛给系统，然后系统选择错误处理器处理


<br>

### 2.3 一道例题

    public class TryCatchFinallyDemo {
   		 public static void  Test()  {

         	 try {
            	   int i =10/0;
          	 }
           	 finally {
               	System.out.println("Test.e ");
           	}

   	 }
   		 public static void main(String [] args) {
       		 try {
          		 Test();
        	} catch (Exception e) {
           		 System.out.print("main.E ");
       		 }

   		 }
	}

>答案 ：Test.e 
main.E 


<br>

### 2.4 throws、throw、try、catch、finally分别代表什么意义？

<br>

> throws、throw、try、catch、finally是一场处理的关键词
> 
>  throws :表示方法体声明异常,声明他会抛出什么类型的异常。
> 
> thorw:表示抛出异常
> 
> try:表示覆盖可能会出现异常的代码段
> 
> catch:表示如果try中出现错误执行catch中的代码  
> 
> finally: 表示不论是否执行catch都执行的代码，一般用于资源的关闭






<br>

### 2.5 finally代码是在return之后还是之前执行？

<br>

> 
> 如果return在try catch语句块中，return执行在finally之前，返回在finally执行之后
> 
>如果return在finally中，return执行之后直接返回


<br>



### 2.6 Java中final,finalize,finally关键字的区别？

<br>

> final 修饰类时候表示不可以继承，修饰方法表示不可以覆盖 修饰变量的时候不可以被修改 修改引用变量的时候不可以指向其他对象
> 
> finalize  是object的方法 表示对该对象垃圾回收的时候清理内存时候回收 ，优先级很低，不一定会执行  
> 




## 3.  异常处理的原则



<br>

> 1.避免捕获通用的异常： 尽量不要捕获Exception捕获具体的 
> 
> 2.尽早的抛出：尽可能早的发现抛出异常，便于精确定位

> 3.延迟捕获： 捕获处理尽可能延迟，让掌握更多信息的作用域处理，比如父类进行相应的处理
